//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFamilay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyFamilyEntities : DbContext
    {
        public MyFamilyEntities()
            : base("name=MyFamilyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAddress> tbAddresses { get; set; }
        public virtual DbSet<tbFamily> tbFamilies { get; set; }
        public virtual DbSet<tbGroup> tbGroups { get; set; }
        public virtual DbSet<tbMember> tbMembers { get; set; }
    }
}
